### ISSUE TITLE
Swap files in repo

### ISSUE THREAD

**Issue by kbuilds** [Glen-Cocoa/mod_tac#1]
Swap files are being committed to the repo. Make sure that you delete them and add `*.swp` to your gitignore

**Comment by Glen-Cocoa** [comment]
Corrected!

**Comment by kbuilds** [comment]
Good.

FYI, Github supports closing issues with a commit message. For this example, the following would commit the code and close this issue:

`git commit -m "removes swap file. adds gitignore file. closes #1`
